# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-04-28
# AGC023 B
# Your code here

$N = gets.chomp.to_i

$S = []
$N.times do
  $S << gets.chomp.split('')
end

def is_good(box, n)
  (0...n).each do |i|
    (i...n).each do |j|
      return false if box[i][j] != box[j][i]
    end
  end
  true
end

count = 0
$N.times do
  count += $N if is_good($S, $N)
  $S.push($S.shift)
end
puts count
