# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-04-28
# AGC023 C
# Your code here

def judge(arr, n)
  box = Array.new(n, 0)
  black = 0
  count = 0
  arr.each do |i|
    count += 1
    if box[i - 1] == 0
      box[i - 1] = 1
      black += 1
    end
    if box[i] == 0
      box[i] = 1
      black += 1
    end
    return count if black == n
  end
end

$N = gets.chomp.to_i

total = {}
(1...$N).to_a.permutation.each do |a|
  # puts a.inspect
  tmp = judge(a, $N)
  total[tmp] ||= 0
  total[tmp] += 1
end

puts total.inspect
