# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-05-09
# ARC002 A
# Your code here
$Y = gets.chomp.to_i

res = if $Y % 400 == 0
        'YES'
      elsif $Y % 100 == 0
        'NO'
      elsif $Y % 4 == 0
        'YES'
      else
        'NO'
    end

puts res
