# Generated by AtcoderGreedy on 2018-05-09
# ARC002 B
# Your code here

require 'date'
date = Date.parse(gets.chomp)

loop do
  if [date.year, date.month, date.day].map(&:to_f).reduce(:/) % 1 < 0.000000000000001
    puts date.strftime('%Y/%m/%d')
    exit(0)
  end
  date += 1
end
