# Generated by AtcoderGreedy on 2018-05-09
# ARC002 C
# Your code here
$N = gets.chomp.to_i

$c = gets.chomp

res = 1_000_000_000_000_000_000
%w[A B X Y].repeated_permutation(4) do |a|
  next if a.uniq.size == 1

  $L = a[0] + a[1]
  $R = a[2] + a[3]
  tmp = $c.dup

  tmp = tmp.gsub($L, 'L')
  tmp = tmp.gsub($R, 'R')
  res = res < tmp.size ? res : tmp.size

  break if $N / 2 == res
end

puts res
