---
:name: indeednow-finala-open
:date: 2015-03-26
:url: https://indeednow-finala-open.contest.atcoder.jp
:task:
  :A:
    :id: '1273'
  :B:
    :id: '1274'
  :C:
    :id: '1275'
  :D:
    :id: '1276'
  :E:
    :id: '1277'
  :F:
    :id: '1284'
