# Generated by AtcoderGreedy on 2018-05-11
# INDEEDNOW-FINALA-OPEN A
# Your code here

$N = gets.chomp.to_i
$a = gets.chomp.split(' ').map(&:to_i)
puts $a.inspect

res = 1_000_000_000_000_000_000

$a.combination(4).each do |c|
  # first = a.max(2).reduce(:+)
  # second = a.min(2).reduce(:+)
  puts c.inspect
  # puts first
  # puts second
  # tmp = (first - second).abs
  # res = tmp < res ? tmp : res
  # break if res == 0
end

puts res
