# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-04-24
# ATC002 A
# Your code here

$R, $C = gets.chomp.split(' ').map(&:to_i)
sy, sx = gets.chomp.split(' ').map(&:to_i)
gy, gx = gets.chomp.split(' ').map(&:to_i)

$c = []

$R.times do
  $c << gets.chomp
end

$queue = [[sy - 1, sx - 1, 0]]
$visited = {}

until $queue.empty?
  y, x, cost = $queue.shift
  next if $visited["#{y}:#{x}"]
  next if $c[y][x] == '#'

  if gy - 1 == y && gx - 1 == x
    puts cost
    exit(0)
  end

  $visited["#{y}:#{x}"] = true

  $queue << [y - 1, x, cost + 1]
  $queue << [y + 1, x, cost + 1]
  $queue << [y, x - 1, cost + 1]
  $queue << [y, x + 1, cost + 1]
end
