# Generated by AtcoderGreedy on 2018-05-12
# ARC097 C
# Your code here

$s = gets.chomp

$K = gets.chomp.to_i - 1

$dict = {}

$s.size.times do |i|
  $dict[$s[i]] ||= []

  (0...5).each do |j|
    $dict[$s[i]] << $s[i..(i + j)]
  end
end

$dict = $dict.sort

group = 0

$dict.each do |item|
  key = item[0]
  values = item[1].uniq.sort

  if group <= $K && $K < values.size + group
    puts values[$K - group]
    break
  else
    group += values.size
  end
end
