# Generated by AtcoderGreedy on 2018-05-12
# ARC097 D
# Your code here
$N, $M = gets.chomp.split(' ').map(&:to_i)

$p = gets.chomp.split(' ').map(&:to_i)

$group = (0...$N).to_a

$rank = Array.new($N, 0)

def find(i)
  $group[i] == i ? i : $group[i] = find($group[i])
end

def union(i, j)
  x = find(i)
  y = find(j)

  if $rank[x] < $rank[y]
    $group[x] = y
  else
    $group[y] = x
    $rank[x] += 1 if $rank[x] = $rank[y]
  end
end

$M.times do
  x, y = gets.chomp.split(' ').map(&:to_i)
  union(x - 1, y - 1)
end

$group_num = {}
$N.times do |i|
  $group_num[find($group[i])] ||= []
  $group_num[find($group[i])] << $p[i]
end

$res = []

count = 0
$N.times do |i|
  count += 1 if find($p[i] - 1) == find(i)
end

puts count
