# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-05-06
# ARC081 C
# Your code here

_ = gets.chomp

$A = gets.chomp.split(' ').map(&:to_i)

$a_hash = {}
$A.each do |i|
  $a_hash[i] ||= 0
  $a_hash[i] += 1
end

long, short = $a_hash.max_by(2) { |k, v| v > 1 ? k : 0 }

if long[1] >= 4
  puts long[0]**2
elsif long[1].to_i > 1 && short[1] > 1
  puts long[0] * short[0]
else
  puts 0
end
