# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-05-06
# ARC081 D
# Your code here

$N = gets.chomp.to_i
$S = []
$S << gets.chomp.split('')
$S << gets.chomp.split('')

$cursor = 0
$res = 1

$prev_type = nil

if $N > 1 && $S[0][0] == $S[0][1]
  $res *= 6
  $prev_type = :yoko
  $cursor += 2

elsif $S[0][0] == $S[1][0]
  $res *= 3
  $prev_type = :tate
  $cursor += 1
end

while $cursor < $N

  if $S[0][$cursor] == $S[1][$cursor]
    $res *= if $prev_type == :yoko
              1
            else
              2
            end
    $prev_type = :tate
    $res %= 1_000_000_007
    $cursor += 1
  else
    $res *= if $prev_type == :yoko
              3
            else
              2
            end
    $prev_type = :yoko
    $res %= 1_000_000_007
    $cursor += 2
  end
end
puts $res
