# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-04-30
# ARC001 A
# Your code here

_ = gets.chomp

$c = gets.chomp.split('')

res = { '1' => 0, '2' => 0, '3' => 0, '4' => 0 }

$c.each do |i|
  res[i] += 1
end
min, max = res.minmax_by { |_, v| v }

puts [max[1], min[1]].join(' ')
