# frozen_string_literal: true

# Generated by AtcoderGreedy on 2018-04-30
# ARC001 B
# Your code here

$A, $B = gets.chomp.split(' ').map(&:to_i)

diff = ($B - $A).abs

count = diff / 10
diff = diff % 10

puts case diff
     when 8, 9
       count + (10 - diff) + 1
     when 6, 7
       count + (diff - 5) + 1
     when 5
       count + 1
     when 3, 4
       count + (5 - diff) + 1
     when 1, 2
       count + diff
     else
       count
    end
