# Generated by AtcoderGreedy on 2018-05-10
# ABC085 C
# Your code here
$N, $Y = gets.chomp.split(' ').map(&:to_i)

if $N * 10_000 < $Y
  puts '-1 -1 -1'
  exit(0)
end

(0..$N).each do |i|
  (0..($N - i)).each do |j|
    if i * 10_000 + j * 5000 + ($N - i - j) * 1000 == $Y
      puts "#{i} #{j} #{($N - i - j)}"
      exit(0)
    end
  end
end

puts '-1 -1 -1'
